# General info
baseurl:     ""
url:         "http://launchwonder.com"
date_format: "%b %-d, %Y"

# Collections
collections_dir: courses
collections:
  algebra1-2:
    title: Algebra 1-2
    output: true
  cs1-2:
    title: Computer Science 1-2
    output: true

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
