# General info
baseurl:     ""
url:         "http://launchwonder.com"
date_format: "%b %-d, %Y"

# Collections
collections_dir: courses
collections:
  algebra:
    title: Algebra
    output: true
  computerscience:
    title: Computer Science
    output: true

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
