# General info
baseurl:     ""
url:         "http://launchwonder.com"
date_format: "%b %-d, %Y"

# Collections
collections_dir: courses
collections:
  algebra:
    title: Algebra
    output: true
  algebrasupport:
    title: Algebra Support
    output: true
  computerscience:
    title: Computer Science
    output: false

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "algebra"
    values:
      layout: "unit"
  - scope:
      path: ""
      type: "algebrasupport"
    values:
      layout: "unit"
  - scope:
      path: ""
      type: "computerscience"
    values:
      layout: "unit"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
